# Generated by Django 2.1 on 2020-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0003_auto_20110413_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
